kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: myapp
spec:
  rules:
    - host: "{{ stage.vars.hostname }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
