kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
spec:
  selector:
    matchLabels:
      process_type: web
  replicas: 1
  template:
    metadata:
      labels:
        process_type: web
    spec:
      containers:
        - name: myapp
          image: "{{ builds.app.image-name }}:{{ commit.ref }}"
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          envFrom:
            - configMapRef:
                name: env-vars
          ports:
            - containerPort: 3000
