kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: myapp
          image: "{{ builds.app.image-name }}:{{ commit.ref }}"
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - rake
            - jobs:work
          envFrom:
            - configMapRef:
                name: env-vars
